// Passages 276-300
{
  id: 'p276',
  title: { en: 'The Bus Driver Who Sang Opera', he: 'נהג האוטובוס ששר אופרה' },
  text: {
    en: `There is a bus driver on the number forty-seven route who has made my morning commute the most entertaining part of my day. His name is Gerald, and he sings opera. Not quietly, not under his breath, but full-throated, window-rattling Italian arias that echo through the bus like we are all sitting in the front row at La Scala. The first time I boarded his bus, I thought someone had left a radio on. Then I realized the sound was coming from the large man behind the wheel, belting out what I later learned was Nessun Dorma while navigating a roundabout. Nobody on the bus knew how to react. An elderly woman clutched her handbag tighter. A teenager removed one earbud, which for a teenager is the equivalent of a standing ovation. I just stood there holding the pole, swaying with each note and each turn. Gerald does not limit himself to Italian. On Tuesdays, he performs German lieder. On Fridays, he attempts Russian pieces that make him sound like a bear who has stubbed his toe. He once told me, between stops, that he had auditioned for a proper opera company years ago but was rejected because, and I quote, they said his voice was so powerful it shook the sheet music off the stands. I am not sure I believe that, but I also cannot prove it wrong. She sells seashells by the seashore, and Gerald sells tickets to the greatest show on public transit. The other passengers have formed unofficial fan clubs. There is a woman who always sits in the third row and claps after every aria. There is a man who brings Gerald espresso in a thermos, because he says every great tenor needs proper coffee. And then there is me, who has rearranged my entire work schedule so I never miss the seven fifteen bus. My boss asked why I refuse to take the earlier bus. I told him the acoustics are terrible on the six forty-five. He did not understand, but Gerald would have. Last week, Gerald attempted a duet with a passenger who claimed to have sung in a church choir. It did not go well. The passenger was flat, Gerald was sharp, and somewhere in the middle a small dog in a carrier bag began to howl. For one brief, glorious moment, it was the worst and most beautiful sound I have ever heard. The whole bus applauded. Gerald took a bow at a red light. I have started to think of the forty-seven bus not as public transportation but as a moving concert hall. The seats are uncomfortable, the schedule is unreliable, and sometimes it smells like someone has brought fish for lunch. But the music, the music is extraordinary. If you ever find yourself in the city with nowhere to be, catch the forty-seven. Bring espresso. Gerald takes requests, but he will only perform them if he deems your selection worthy. Choose wisely.`,
    he: `יש נהג אוטובוס בקו ארבעים ושבע שהפך את הנסיעה שלי בבוקר לחלק הכי משעשע ביום. שמו ג'רלד, והוא שר אופרה. לא בשקט, לא מתחת לשפם, אלא אריות איטלקיות בקול מלא שמרעידות את החלונות ומהדהדות באוטובוס כאילו כולנו יושבים בשורה הראשונה בלה סקאלה. בפעם הראשונה שעליתי לאוטובוס שלו, חשבתי שמישהו שכח רדיו דלוק. אז הבנתי שהצליל בא מהגבר הגדול מאחורי ההגה, שמזמר את מה שאחר כך גיליתי שזה נסון דורמה תוך כדי ניווט בכיכר. אף אחד באוטובוס לא ידע איך להגיב. אישה מבוגרת אחזה בתיק שלה חזק יותר. נער הוריד אוזנייה אחת, מה שאצל נערים שווה ערך למחיאות כפיים סוערות. אני פשוט עמדתי שם ונאחזתי במוט, מתנדנד עם כל תו וכל פנייה. ג'רלד לא מגביל את עצמו לאיטלקית. בימי שלישי הוא מבצע לידר גרמני. בימי שישי הוא מנסה יצירות רוסיות שגורמות לו להישמע כמו דוב שדרך על לגו. פעם הוא סיפר לי, בין תחנות, שהוא עשה אודישן לחברת אופרה אמיתית לפני שנים אבל נדחה כי, ואני מצטט, הם אמרו שהקול שלו כל כך חזק שהוא הפיל את התווים מהעמודים. אני לא בטוח שאני מאמין לזה, אבל גם לא יכול להוכיח שזה לא נכון. שרה שרה שיר שמח, שיר שמח שרה שרה, וג'רלד שר אריות במופע הכי טוב בתחבורה ציבורית. הנוסעים האחרים הקימו מועדוני מעריצים לא רשמיים. יש אישה שתמיד יושבת בשורה השלישית ומוחאת כפיים אחרי כל אריה. יש גבר שמביא לג'רלד אספרסו בתרמוס, כי הוא אומר שכל טנור גדול צריך קפה טוב. ואז יש אותי, שסידרתי מחדש את כל לוח הזמנים שלי בעבודה כדי לא לפספס את האוטובוס של שבע וחמש עשרה. הבוס שלי שאל למה אני מסרב לקחת את האוטובוס המוקדם יותר. אמרתי לו שהאקוסטיקה נוראית בשש ארבעים וחמש. הוא לא הבין, אבל ג'רלד היה מבין. בשבוע שעבר, ג'רלד ניסה דואט עם נוסע שטען ששר פעם במקהלת כנסייה. זה לא הלך טוב. הנוסע היה צורם, ג'רלד היה חד מדי, ואיפשהו באמצע כלב קטן בתיק נשיאה התחיל ליילל. לרגע אחד קצר ומפואר, זה היה הצליל הכי גרוע והכי יפה ששמעתי אי פעם. כל האוטובוס מחא כפיים. ג'רלד השתחווה ברמזור אדום. התחלתי לחשוב על קו ארבעים ושבע לא כתחבורה ציבורית אלא כאולם קונצרטים נייד. המושבים לא נוחים, לוח הזמנים לא אמין, ולפעמים מריחים כאילו מישהו הביא דג לצהריים. אבל המוזיקה, המוזיקה היא יוצאת דופן. אם פעם אתם מוצאים את עצמכם בעיר בלי שום מקום להגיע אליו, תעלו על קו ארבעים ושבע. תביאו אספרסו. ג'רלד מקבל בקשות, אבל הוא יבצע אותן רק אם הוא שופט שהבחירה שלכם ראויה. תבחרו בחוכמה.`,
  },
  difficulty: 'medium',
  targetWPM: 100,
},
{
  id: 'p277',
  title: { en: 'The Great Sock Conspiracy', he: 'הקונספירציה הגדולה של הגרביים' },
  text: {
    en: `I have spent years investigating one of the greatest unsolved mysteries of domestic life: where do socks go when they disappear in the laundry? I have compiled data, conducted experiments, and even installed a camera near my washing machine. The results are disturbing. Over the past three years, I have lost exactly forty-one socks. Not forty-one pairs. Forty-one individual socks. Each time, it is the same story. I put a matched pair into the machine. I hear the water fill, the drum spin, the cycle complete. I open the door and reach inside. One sock. Just one. The other has simply ceased to exist. My wife thinks I am being dramatic. She says I probably drop them behind the machine. I pulled the machine out from the wall last month. Behind it I found two dust bunnies the size of small cats, a pen I lost in two thousand and nineteen, and a birthday card from my mother that said she was proud of me. No socks. I have developed several theories. The first is that washing machines contain a small portal to another dimension. Every few cycles, the portal activates and claims a sock as tribute. Somewhere in a parallel universe, there is a mountain of single socks and the beings who live there are very confused. My second theory involves the dryer. Peter Piper picked a peck of pickled peppers, but my dryer picks a sock every single week. I believe the dryer has become sentient and collects socks the way some people collect stamps. My third and most disturbing theory is that the socks leave voluntarily. Think about it. Socks live a terrible life. They are stuffed into dark shoes, stepped on all day, and then thrown into a hamper that smells like a gym bag that has given up on life. Can you blame them for escaping? I recently tried an experiment. I safety-pinned each pair of socks together before putting them in the wash. When the cycle ended, I had all my socks. Every single one. But they were stretched and misshapen, as if they had been trying desperately to pull apart. As if they had been trying to escape. I unpinned them and held them up. They looked defeated. I felt guilty. Now I have a new system. I have accepted the loss. Every month, I buy a pack of identical black socks. When one disappears, it does not matter, because they are all the same. I have outsmarted the conspiracy. Or so I thought. Last Tuesday, I opened the dryer to find that three identical black socks had vanished and been replaced by a single bright pink sock that belongs to nobody in my household. The conspiracy is bigger than I imagined. They are not just taking socks. They are sending messages. I am not sure what the pink sock means, but I am sleeping with one eye open. Red lorry, yellow lorry, red lorry, yellow lorry, and somewhere a pink sock is laughing at me.`,
    he: `כבר שנים שאני חוקר אחת התעלומות הגדולות והלא פתורות של החיים הביתיים: לאן נעלמות גרביים בכביסה? אספתי נתונים, ביצעתי ניסויים, ואפילו התקנתי מצלמה ליד מכונת הכביסה. התוצאות מטרידות. בשלוש השנים האחרונות, איבדתי בדיוק ארבעים ואחת גרביים. לא ארבעים ואחד זוגות. ארבעים ואחת גרביים בודדות. כל פעם, אותו סיפור. אני שם זוג תואם למכונה. אני שומע את המים מתמלאים, את התוף מסתובב, את המחזור מסתיים. אני פותח את הדלת ומושיט יד פנימה. גרב אחת. רק אחת. השנייה פשוט חדלה להתקיים. אשתי חושבת שאני דרמטי. היא אומרת שכנראה אני מפיל אותן מאחורי המכונה. הזזתי את המכונה מהקיר בחודש שעבר. מאחוריה מצאתי שני ארנבוני אבק בגודל של חתולים קטנים, עט שאיבדתי באלפיים ותשע עשרה, וכרטיס יום הולדת מאמא שלי שכתבה שהיא גאה בי. אפס גרביים. פיתחתי כמה תיאוריות. הראשונה היא שמכונות כביסה מכילות פורטל קטן לממד אחר. כל כמה מחזורים, הפורטל מופעל ותובע גרב כמס. איפשהו ביקום מקביל, יש הר של גרביים בודדות והיצורים שגרים שם מאוד מבולבלים. התיאוריה השנייה שלי קשורה למייבש. גנן גידל דגן בגן, דגן גדול גדל בגן, אבל המייבש שלי גונב גרב כל שבוע. אני מאמין שהמייבש הפך לישות בעלת תודעה ואוסף גרביים כמו שיש אנשים שאוספים בולים. התיאוריה השלישית והמטרידה ביותר שלי היא שהגרביים עוזבות מרצון. תחשבו על זה. גרביים חיות חיים נוראיים. הן נדחסות לנעליים חשוכות, דורכים עליהן כל היום, ואז זורקים אותן לסל כביסה שמריח כמו תיק ספורט שוויתר על החיים. אפשר להאשים אותן שהן בורחות? לאחרונה ניסיתי ניסוי. הצמדתי כל זוג גרביים יחד עם סיכת ביטחון לפני שהכנסתי אותן לכביסה. כשהמחזור הסתיים, היו לי כל הגרביים. כל אחת ואחת. אבל הן היו מתוחות ומעוותות, כאילו ניסו בנואשות להיפרד. כאילו ניסו לברוח. הסרתי את הסיכות והרמתי אותן. הן נראו מובסות. הרגשתי אשם. עכשיו יש לי שיטה חדשה. השלמתי עם האובדן. כל חודש, אני קונה חבילה של גרביים שחורות זהות. כשאחת נעלמת, זה לא משנה, כי כולן אותו דבר. עקפתי את הקונספירציה. או שכך חשבתי. ביום שלישי האחרון, פתחתי את המייבש וגיליתי ששלוש גרביים שחורות זהות נעלמו והוחלפו בגרב ורודה בוהקת אחת שלא שייכת לאף אחד במשק הבית שלי. הקונספירציה גדולה ממה שדמיינתי. הם לא רק לוקחים גרביים. הם שולחים מסרים. אני לא בטוח מה הגרב הוורודה אומרת, אבל אני ישן עם עין אחת פקוחה. נחש נשך נחש, כי נחש נחש שנחש נשך נחש, ואיפשהו גרב ורודה צוחקת עליי.`,
  },
  difficulty: 'medium',
  targetWPM: 100,
},
{
  id: 'p278',
  title: { en: 'Learning to Ride a Bike at Thirty-Five', he: 'ללמוד לרכוב על אופניים בגיל שלושים וחמש' },
  text: {
    en: `Nobody tells you that learning to ride a bicycle as an adult is an exercise in public humiliation. As a child, you fall off a bike and people rush to help you, give you a bandage, and tell you how brave you are. As a thirty-five-year-old man falling off a bike in a public park, people just stare. Some take photos. One woman asked if I was doing performance art. I was not. I was doing my best, and my best involved a lot of falling. It started when my daughter, who is six, asked why I never ride bikes with her. I told her it was because I preferred walking. The truth, which I had hidden for decades, was that I never learned. My parents tried when I was seven. After I rode directly into a parked car, a mailbox, and then a very patient dog, they decided I was meant for other things. Like staying indoors. But my daughter looked at me with those big eyes and said please, and so I found myself at a bike shop buying a bicycle built for a man my size. The shop owner asked what kind of riding I planned to do. I said survival. She thought I was joking. On my first attempt, I managed to stay upright for roughly four seconds before veering into a hedge. The hedge was actually quite comfortable and I considered staying there. But my daughter was watching, so I extracted myself, picked leaves out of my hair, and tried again. The second attempt was worse. I discovered that when you panic on a bicycle, your instinct is to pedal faster, which is the opposite of helpful. I shot across the path like a missile with no guidance system. How much wood would a woodchuck chuck if a woodchuck could chuck wood? I do not know, but I can tell you exactly how much bush a grown man can chuck when he flies off a bicycle at speed. It took three weekends of practice. Three weekends of wobbling, falling, apologizing to joggers, and frightening small children. But on the fourth weekend, something clicked. I pedaled and did not fall. I turned and did not crash. I even managed to wave at my daughter, which nearly killed me, but I survived. Now I ride every weekend. I am slow. I am cautious. I wear more protective gear than a professional hockey player. But I ride. My daughter rides beside me and sometimes she looks over and smiles, and in those moments I forget about every bruise, every hedge, and every judgmental jogger. She sells seashells by the seashore, and I sell the idea that it is never too late to learn something new. Even if that something leaves you covered in leaves and missing a bit of dignity. Last week, my daughter asked if I wanted to learn to skateboard. I told her I preferred walking. Some lessons do not need to be learned twice.`,
    he: `אף אחד לא אומר לך שללמוד לרכוב על אופניים כמבוגר זה תרגיל בהשפלה פומבית. כילד, אתה נופל מאופניים ואנשים רצים לעזור לך, נותנים לך פלסטר, ואומרים לך כמה אתה אמיץ. כגבר בן שלושים וחמש שנופל מאופניים בפארק ציבורי, אנשים פשוט בוהים. חלקם מצלמים. אישה אחת שאלה אם אני עושה אמנות מופע. לא עשיתי. עשיתי כמיטב יכולתי, והכמיטב שלי כלל הרבה נפילות. זה התחיל כשהבת שלי, בת שש, שאלה למה אני אף פעם לא רוכב איתה על אופניים. אמרתי לה שזה כי אני מעדיף ללכת ברגל. האמת, שהסתרתי עשרות שנים, היא שמעולם לא למדתי. ההורים שלי ניסו כשהייתי בן שבע. אחרי שרכבתי ישר לתוך מכונית חונה, תיבת דואר, ואז כלב מאוד סבלני, הם החליטו שאני מיועד לדברים אחרים. כמו להישאר בפנים. אבל הבת שלי הסתכלה עליי עם העיניים הגדולות האלה ואמרה בבקשה, ואז מצאתי את עצמי בחנות אופניים קונה אופניים בנויים לגבר בגודל שלי. בעלת החנות שאלה איזה סוג רכיבה אני מתכנן. אמרתי הישרדות. היא חשבה שאני צוחק. בניסיון הראשון שלי, הצלחתי להישאר זקוף בערך ארבע שניות לפני שסטיתי לתוך גדר חיה. הגדר החיה הייתה למעשה די נוחה ושקלתי להישאר שם. אבל הבת שלי צפתה, אז חילצתי את עצמי, הוצאתי עלים מהשיער, וניסיתי שוב. הניסיון השני היה גרוע יותר. גיליתי שכשנכנסים לפאניקה על אופניים, האינסטינקט הוא לדווש מהר יותר, שזה ההפך ממועיל. דהרתי על פני השביל כמו טיל בלי מערכת ניווט. קרקר קרקר קרקר, קרקר קרקר בקרקס, ואני הייתי הליצן הראשי בקרקס של הפארק. לקח שלושה סופי שבוע של תרגול. שלושה סופי שבוע של התנדנדות, נפילה, התנצלות בפני רצים, והפחדת ילדים קטנים. אבל בסוף השבוע הרביעי, משהו הסתדר. דיוושתי ולא נפלתי. פניתי ולא התרסקתי. אפילו הצלחתי לנופף לבת שלי, מה שכמעט הרג אותי, אבל שרדתי. עכשיו אני רוכב כל סוף שבוע. אני איטי. אני זהיר. אני לובש יותר ציוד מגן משחקן הוקי מקצועי. אבל אני רוכב. הבת שלי רוכבת לידי ולפעמים היא מסתכלת ומחייכת, וברגעים האלה אני שוכח מכל חבורה, כל גדר חיה, וכל רץ שיפוטי. שרה שרה שיר שמח, שיר שמח שרה שרה, ואני מוכר את הרעיון שאף פעם לא מאוחר מדי ללמוד משהו חדש. גם אם המשהו הזה משאיר אותך מכוסה בעלים וחסר קצת כבוד. בשבוע שעבר, הבת שלי שאלה אם אני רוצה ללמוד סקייטבורד. אמרתי לה שאני מעדיף ללכת ברגל. יש שיעורים שלא צריך ללמוד פעמיים.`,
  },
  difficulty: 'hard',
  targetWPM: 110,
},
{
  id: 'p279',
  title: { en: 'My Cat Judges Me', he: 'החתול שלי שופט אותי' },
  text: {
    en: `I am fairly certain my cat thinks I am an idiot. His name is Professor Whiskers, which my wife chose because she said he looked distinguished. She was right. He has the permanent expression of a university dean who has just read a particularly disappointing thesis. Every morning, I wake up to find him sitting on my chest, staring at me with what I can only describe as profound contempt. Not hunger. Not affection. Contempt. He watches me get dressed and I swear his eyes narrow when I choose the wrong shirt. He watches me make breakfast and turns away when I burn the toast, as if my failure is too painful for him to witness. I tried to explain to my wife that the cat is judging us. She said I was projecting. Then Professor Whiskers knocked her coffee off the table while maintaining eye contact, and she had to admit there might be something to my theory. The thing about Professor Whiskers is that he has standards. He will only eat from a ceramic bowl. Not plastic, not metal. Ceramic. And it has to be placed on the left side of the kitchen, at a slight angle. I know this because every time I put it on the right side, he sits next to it without eating and looks at me until I move it. He does not meow. He does not paw at it. He simply sits and radiates disappointment until the situation is corrected. Betty Botter bought some butter, but said the butter was bitter. Professor Whiskers would never tolerate bitter butter. He would simply stare at it until better butter appeared. He has a chair. Not a cat bed, not a cushion. A chair. The blue armchair in the living room that used to be mine. I made the mistake of getting up one afternoon to get a glass of water. When I came back, he was in the chair. I stood there for a moment, considering my options. He looked at me as if to say, you made your choice. I sat on the floor. That was two years ago. I have not sat in that chair since. He has claimed it with the quiet authority of a king ascending a throne. Sometimes at night, I hear him walking around the house. Not playing, not hunting. Walking. Inspecting. Making sure everything meets his standards. I imagine him checking the locks, examining the furniture for dust, and making small disapproving sounds at the state of the bookshelf. Peter Piper picked a peck of pickled peppers, but Professor Whiskers would never pick anything. He would wait for it to be presented to him on a ceramic plate, at the correct angle, in the proper room. My wife recently suggested we get a second cat for company. Professor Whiskers heard this from across the room. He turned his head slowly, gave us both a look that could freeze water, and walked away with his tail held high. We did not get a second cat. We know who runs this household, and it is not the two humans who pay the mortgage.`,
    he: `אני די בטוח שהחתול שלי חושב שאני אידיוט. שמו פרופסור וויסקרס, שם שאשתי בחרה כי היא אמרה שהוא נראה מכובד. היא צדקה. יש לו את ההבעה הקבועה של דיקן אוניברסיטה שזה עתה קרא עבודת גמר מאכזבת במיוחד. כל בוקר, אני מתעורר ומגלה אותו יושב על החזה שלי, בוהה בי במה שאני יכול לתאר רק כבוז עמוק. לא רעב. לא חיבה. בוז. הוא צופה בי מתלבש ואני נשבע שהעיניים שלו מצטמצמות כשאני בוחר את החולצה הלא נכונה. הוא צופה בי מכין ארוחת בוקר ומסתובב כשאני שורף את הטוסט, כאילו הכישלון שלי כואב מדי בשבילו לצפות בו. ניסיתי להסביר לאשתי שהחתול שופט אותנו. היא אמרה שאני מקרין. אז פרופסור וויסקרס הפיל לה את הקפה מהשולחן תוך שמירה על קשר עין, והיא הייתה חייבת להודות שאולי יש משהו בתיאוריה שלי. העניין עם פרופסור וויסקרס הוא שיש לו סטנדרטים. הוא יאכל רק מקערת קרמיקה. לא פלסטיק, לא מתכת. קרמיקה. וצריך לשים אותה בצד שמאל של המטבח, בזווית קלה. אני יודע את זה כי כל פעם שאני שם אותה בצד ימין, הוא יושב לידה בלי לאכול ומסתכל עליי עד שאני מזיז. הוא לא מיאומיאו. הוא לא טורף בכפה. הוא פשוט יושב ומקרין אכזבה עד שהמצב מתוקן. גנן גידל דגן בגן, דגן גדול גדל בגן, אבל פרופסור וויסקרס לא היה סובל דגן רגיל. הוא פשוט היה בוהה בו עד שדגן איכותי יותר היה מופיע. יש לו כיסא. לא מיטת חתול, לא כרית. כיסא. הכורסה הכחולה בסלון שפעם הייתה שלי. עשיתי את הטעות לקום אחד אחר הצהריים להביא כוס מים. כשחזרתי, הוא היה בכורסה. עמדתי שם רגע, שוקל את האפשרויות שלי. הוא הסתכל עליי כאילו אומר, עשית את הבחירה שלך. ישבתי על הרצפה. זה היה לפני שנתיים. לא ישבתי בכורסה הזו מאז. הוא תבע אותה בסמכות שקטה של מלך העולה על כס המלכות. לפעמים בלילה, אני שומע אותו מסתובב בבית. לא משחק, לא צד. מסתובב. בודק. מוודא שהכול עומד בסטנדרטים שלו. אני מדמיין אותו בודק את המנעולים, בוחן את הרהיטים לאבק, ומשמיע קולות של אי-אישור קטנים על מצב מדף הספרים. פרפר פרפר פרח, פרח פרח פרפר, אבל פרופסור וויסקרס לא היה מתקרב לפרח. הוא היה מחכה שיגישו לו אותו על צלחת קרמיקה, בזווית הנכונה, בחדר המתאים. אשתי הציעה לאחרונה שנביא חתול שני לחברה. פרופסור וויסקרס שמע את זה מהצד השני של החדר. הוא סובב את הראש לאט, נתן לנו שנינו מבט שיכול להקפיא מים, והלך משם עם הזנב מורם. לא הבאנו חתול שני. אנחנו יודעים מי מנהל את משק הבית הזה, ואלה לא שני בני האדם שמשלמים את המשכנתא.`,
  },
  difficulty: 'hard',
  targetWPM: 110,
},
{
  id: 'p280',
  title: { en: 'The Automatic Door That Hates Me', he: 'הדלת האוטומטית ששונאת אותי' },
  text: {
    en: `There is an automatic door at my local supermarket that has decided I am not worthy of entry. Every other person walks up to it and it opens smoothly, welcoming them inside like a gracious host. When I approach, nothing happens. I stand there waving my arms like I am directing an airplane on a runway. I jump up and down. I do a little dance. The door remains closed. It is as if the sensor has developed a personal grudge against me. This has been going on for months. I first noticed it in January. I walked toward the door, carrying two bags of groceries I had bought at another store. The door did not open. The woman behind me walked up and it opened immediately. She gave me a look. That look. The one that says, how can you not operate a door. I wanted to explain that the door was the problem, not me. But how do you explain to a stranger that a door has chosen you as its enemy? I have tried everything. I have approached slowly. I have approached quickly. I have tried walking at the exact pace of other shoppers who trigger the sensor without any issue. Nothing works. A proper copper coffee pot, people say, but I say a proper working door is all I ask. Last week, I tried a new strategy. I waited for someone else to approach and then walked very close behind them, hoping to slip through while the door was open. It worked, but the person in front of me stopped suddenly and I walked directly into their back. They dropped their shopping list and their reading glasses. I apologized profusely while the door closed behind us with what I can only describe as a satisfied hum. My friend works at the supermarket and I asked him to check the sensor. He stood outside and walked toward the door twenty times. It opened every single time. Then I tried. Nothing. He looked at me with concern. He suggested maybe I was approaching at the wrong angle. So I tried different angles. Straight on. From the left. From the right. At a forty-five degree angle. Backward. Nothing. The door opened for a child on a scooter, a woman with a stroller, and an elderly man with a walker. It would not open for me. She sells seashells by the seashore, and I sell my dignity every time I stand outside this supermarket flailing at a door that refuses to acknowledge my existence. I have started using the manual door on the other side of the building. It is heavier than it needs to be and it squeaks in a way that makes everyone in the store turn and look. But at least it opens. Sometimes I walk past the automatic door just to test it. Still nothing. But last Tuesday, I could have sworn it opened about two inches and then closed again. As if it was teasing me. As if it wanted me to know that it could open, it simply chose not to. I have accepted my fate. Some people have enemies in high places. I have an enemy in a sliding door. And somehow, that is worse.`,
    he: `יש דלת אוטומטית בסופרמרקט המקומי שלי שהחליטה שאני לא ראוי להיכנס. כל אדם אחר ניגש אליה והיא נפתחת בחלקות, מקבלת אותם פנימה כמו מארחת אדיבה. כשאני מתקרב, שום דבר לא קורה. אני עומד שם מנופף בידיים כאילו אני מכוון מטוס על מסלול. אני קופץ למעלה ולמטה. אני עושה ריקוד קטן. הדלת נשארת סגורה. כאילו החיישן פיתח טינה אישית נגדי. זה נמשך כבר חודשים. שמתי לב לראשונה בינואר. הלכתי לכיוון הדלת, נושא שתי שקיות מצרכים שקניתי בחנות אחרת. הדלת לא נפתחה. האישה מאחוריי ניגשה והיא נפתחה מיד. היא נתנה לי מבט. המבט הזה. זה שאומר, איך אתה לא מסוגל להפעיל דלת. רציתי להסביר שהדלת היא הבעיה, לא אני. אבל איך מסבירים לזרה שדלת בחרה בך כאויב? ניסיתי הכול. ניגשתי לאט. ניגשתי מהר. ניסיתי ללכת בדיוק בקצב של קונים אחרים שמפעילים את החיישן בלי שום בעיה. שום דבר לא עובד. נחש נשך נחש, כי נחש נחש שנחש נשך נחש, ואני מרגיש כמו נחש שמנסה לנשוך דלת שלא זזה. בשבוע שעבר, ניסיתי אסטרטגיה חדשה. חיכיתי שמישהו אחר יתקרב ואז הלכתי מאוד צמוד מאחוריו, בתקווה להחליק פנימה בזמן שהדלת פתוחה. זה עבד, אבל האדם שלפניי עצר פתאום ואני הלכתי ישר לתוך הגב שלו. הוא הפיל את רשימת הקניות ואת משקפי הקריאה שלו. התנצלתי בצורה מוגזמת בזמן שהדלת נסגרה מאחורינו עם מה שאני יכול לתאר רק כזמזום מרוצה. חבר שלי עובד בסופרמרקט וביקשתי ממנו לבדוק את החיישן. הוא עמד בחוץ והלך לכיוון הדלת עשרים פעם. היא נפתחה כל פעם. אז אני ניסיתי. כלום. הוא הסתכל עליי בדאגה. הוא הציע שאולי אני ניגש בזווית לא נכונה. אז ניסיתי זוויות שונות. ישר. משמאל. מימין. בזווית של ארבעים וחמש מעלות. אחורה. כלום. הדלת נפתחה לילד על קורקינט, אישה עם עגלת תינוק, וגבר מבוגר עם הליכון. היא לא נפתחה בשבילי. שרה שרה שיר שמח, שיר שמח שרה שרה, ואני מאבד את הכבוד שלי כל פעם שאני עומד מחוץ לסופרמרקט הזה מנופף לדלת שמסרבת להכיר בקיומי. התחלתי להשתמש בדלת הידנית בצד השני של הבניין. היא כבדה יותר ממה שצריך וחורקת בצורה שגורמת לכולם בחנות להסתובב ולהסתכל. אבל לפחות היא נפתחת. לפעמים אני עובר ליד הדלת האוטומטית רק כדי לבדוק. עדיין כלום. אבל ביום שלישי האחרון, הייתי יכול להישבע שהיא נפתחה בערך שני סנטימטרים ואז נסגרה שוב. כאילו היא מתגרה בי. כאילו היא רצתה שאדע שהיא יכולה להיפתח, היא פשוט בוחרת שלא. השלמתי עם הגורל שלי. לחלק מהאנשים יש אויבים במקומות גבוהים. לי יש אויב בדלת הזזה. ואיכשהו, זה יותר גרוע.`,
  },
  difficulty: 'easy',
  targetWPM: 90,
},
